name: PR label remover

on:
  pull_request:
    types: [closed]

jobs:
  remove_labels:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            // 削除したいラベルを指定
            const labelsToBeDeleted = ["Don\'t Merge", "High Priority", "WIP"]
            
            // 今ついているラベルを取得
            const { repository } = await github.graphql(`
              query fetchPullRequestWithLabels($owner: String!, $repo: String!, $number: Int!){
                repository(owner: $owner, name: $repo) {
                  pullRequest(number: $number) {
                    id
                    labels(first: 100) {
                      nodes {
                        id
                        name
                      }
                    }
                  }
                }
              }
            `, {
              owner: context.repo.owner,
              repo: context.repo.repo,
              number: context.payload.pull_request.number,
            })
            const pullRequestID = repository.pullRequest.id
            const prLabels = repository.pullRequest.labels.nodes
            const targetLabelIDs = prLabels
              .filter(prLabel => labelsToBeDeleted.includes(prLabel.name))
              .map(prLabel => prLabel.id)
            
            // 対象のラベルがないなら終了
            if (targetLabelIDs.length === 0) {
              return
            }
            
            // 対象のラベルがあれば削除する
            await github.graphql(`
              mutation removeLabelsFromPullRequest($pullRequestID: ID!, $targetLabelIDs: [ID!]!) { 
                removeLabelsFromLabelable(input: { labelableId: $pullRequestID, labelIds: $targetLabelIDs }) {
                  clientMutationId
                }
              }
            `, {
              pullRequestID,
              targetLabelIDs,
            })

